### ISSUE TITLE
Support for Isabelle2024

### ISSUE THREAD

**Issue by BookWood7th** [dominique-unruh/scala-isabelle#14]
The internal ML structures of Isabelle have changed in the last Isabelle update. This makes scala-isabelle not work for the new Isabelle version.

Is an update to scala-isabelle planned to ensure compatibility with the new Isabelle version?

**Comment by marcinwrochna** [comment]
Fortunately there's only two changes that seem to matter:
A. Mutex is now Thread.Mutex
B. `Isabelle/ML explicitly rejects 'handle' with catch-all patterns. INCOMPATIBILITY, better use \<^try>‹...› with 'catch' or 'finally', or as last resort declare [[ML_catch_all]] within the theory context.` (citing the [release notes](https://isabelle.in.tum.de/dist/Isabelle2024/doc/NEWS.html)).

I have [a branch](https://github.com/dominique-unruh/scala-isabelle/compare/master...marcinwrochna:scala-isabelle:test2024) that works with Isabelle2024 by fixing A. and doing the `ML_catch_all` workaround for B., but:
1. It's not backward compatible (I didn't add version checks).
2. It would be better to replace the catch-alls with try-catch-finally in Scala_Isabelle_Master_Control_Program.thy instead of the workaround.
3. I auto-removed trailing spaces which makes the commit diffs messy.

Unfortunately I personally don't have the time to make a proper merge request currently.

**Comment by dominique-unruh** [comment]
I will deal with this in the next few days. (I did it for one of the RCs and then forgot to finish it up when 2024 came out.)

**Comment by dominique-unruh** [comment]
ee5158b72d87dbdcc97ad800f9f5ed36bd6d320e supports Isabelle2024.
A release is in preparation.

**Comment by marcinwrochna** [comment]
Thanks a lot!

**Comment by dominique-unruh** [comment]
Isabelle2024 support is now in release 0.4.3-RC1.
